### ISSUE TITLE
Impossible de lancer le projet à cause de conflit de migration

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#438]
Je n'arrive plus à lancer le projet à cause de conflit de migration : 
Si je lance le server, il me dit qu'il faut que je fasse un migrate.
```
$ python3 manage.py migrate               
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0036_auto_20210322_0115, 0034_auto_20210321_2255, 0033_auto_20210322_1938, 0038_auto_20210323_0848, 0034_auto_20210401_1732 in orgues).
To fix them run 'python manage.py makemigrations --merge'
$ python3 manage.py makemigrations --merge
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/commands/makemigrations.py", line 133, in handle
    return self.handle_merge(loader, conflicts)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/commands/makemigrations.py", line 261, in handle_merge
    raise ValueError("Could not find common ancestor of %s" % migration_names)
ValueError: Could not find common ancestor of {'0038_auto_20210323_0848', '0036_auto_20210322_0115', '0034_auto_20210321_2255', '0033_auto_20210322_1938', '0034_auto_20210401_1732'}
```
Je suis sur la branche master.
J'ai supprimé la base sqlite, mais j'ai toujours le même soucis.

**Comment by patou** [comment]
Avec les derniers changements dans master, cela fonctionne.
